title: 'Social Media Settings'
data:
  facebook_link: 'https://www.facebook.com/PhotoboothMiroirMagic'
  instagram_link: 'https://www.instagram.com/photobooth.miroirmagic/'
  linkedin_link: 'https://www.linkedin.com/company/location-borne-photobooth-miroir-magic/'
  youtube_link: 'https://www.youtube.com/@LawrenceBanahanPhotographe'
  pinterest_link: 'https://www.pinterest.com/photoboothmiroirmagic'
  tiktok_link: 'https://www.tiktok.com/@photobooth.miroirmagic'
